"""message

Revision ID: 57a773dc8e65
Revises: e504657ca40e
Create Date: 2025-02-09 15:42:40.513774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a773dc8e65'
down_revision = 'e504657ca40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('purchase_forecast', sa.Float(), nullable=False),
    sa.Column('sale_forecast', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecasts')
    # ### end Alembic commands ###
