"""update

Revision ID: e504657ca40e
Revises: 
Create Date: 2025-01-27 17:41:14.456755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e504657ca40e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('ItemID', sa.Integer(), nullable=False),
    sa.Column('SKU', sa.String(length=64), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Unit', sa.String(length=64), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('CategoryID', sa.Integer(), nullable=True),
    sa.Column('CurrentStock', sa.Integer(), nullable=False),
    sa.Column('ReorderLevel', sa.Integer(), nullable=True),
    sa.Column('UnitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['CategoryID'], ['categories.CategoryID'], ),
    sa.PrimaryKeyConstraint('ItemID')
    )
    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'inventory', ['ItemID'], ['ItemID'])

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'inventory', ['ItemID'], ['ItemID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('inventory')
    # ### end Alembic commands ###
